[package]
name = "iot_sensors"
version = "0.1.0"
edition = "2024"

[dependencies]
bme280 = { version = "0.5.1", features = ["serde"] }
linux-embedded-hal = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }
